### ISSUE TITLE
Question about XCode run script to compile K/N

### ISSUE THREAD

**Issue by khairilushan** [ilmat192/Kotlin-Native-Gradle-Experiments#1]
Hi I saw your comment on this issue ([#1583](https://github.com/JetBrains/kotlin-native/issues/1583#issuecomment-389115746)) about the run script for XCode to compile the K/N to `.framework` format. 
Is that run script still applicable when we're using `kotlin-platform-native` plugin instead of `konan`?
Previously I found it work when still using `konan`, but after trying to use `kotlin-native-platform`, I always got error from XCode
```
ld: framework not found my_native_module_name
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ilmat192** [comment]
No, currently `kotlin-platform-native` doesn't support setting output directories using project properties, so it's better to use `konan` with XCode. But you still can copy framwork produced in the "right" place manually (see https://kotlinlang.slack.com/archives/C3SGXARS6/p1533508509000061):

```
sourceSets.main.component {
    baseName.set("Greeting")
}

task copyFramework() {
    dependsOn('compileDebugIos_x64KotlinNative')
    doLast {
        if (project.hasProperty("konan.configuration.build.dir")) {
            def srcFile = tasks['compileDebugIos_x64KotlinNative'].outputFile
            def targetDir = getProperty("konan.configuration.build.dir") + "/Greeting.framework"
            copy {
                from srcFile
                into targetDir
            }
        }
    }
}

```

**Comment by khairilushan** [comment]
Hi Thank you so much for that answer. Will try it. Sorry if this seems unrelated with anything from this repo. A bit desperate to find someone to ask. haha

Btw how do we make sure if the copying process is done correctly? which path to check to make sure?

**EDIT:**
Ah never mind. Got another sample from [this PR](https://github.com/JetBrains/kotlin-mpp-example/pull/3/files).
